os:
  linux
language:
  python

env:
  global:
    - MOZ_HEADLESS=1

addons:
  firefox: latest
  apt:
    packages:
      firefox-geckodriver
python:
  - 3.7

install:
  - pip install -r requirements.txt

script:
  - cd superlists
  - python manage.py migrate
  - python manage.py makemigrations
  - python manage.py test lists
  - python manage.py test functional_tests