os:
  linux
language:
  python
addons:
  firefox: latest
python:
  - 3.7

install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C $(pwd)/bin
  - export PATH=$(pwd)/bin:$PATH
  - pip install -r requirements.txt


script:
  - cd superlists
  - python manage.py migrate
  - python manage.py makemigrations
  - python manage.py test lists
  - python manage.py test functional_tests