os:
  linux
language:
  python
addons:
  firefox: "57.0"
  apt:
    packages:
      firefox-geckodriver
python:
  - 3.7

install:
  - pip install -r requirements.txt

script:
  - cd superlists
  - python manage.py migrate
  - python manage.py makemigrations
  - python manage.py test lists
  - python manage.py test functional_tests